name: Run test
on: push
jobs:
  test:
    runs-on: ubuntu-latest
    permissions:
      # Give the default GITHUB_TOKEN write permission to commit and push the
      # added or changed files to the repository.
      contents: write
    steps:
        - name: Checkout master
          uses: actions/checkout@v3
          
        - name: Get changed files
          id: changed-files
          uses: tj-actions/changed-files@v35
          with:
            files: |
              **/*.py
          
        - name: Upgrade pip
          run: pip install --upgrade pip
          
        - name: Install ruff
          run: pip install ruff
          
        - name: Ruff check          
          run: ruff check ${{ steps.changed-files.outputs.all_changed_files }}
          
        - name: Push back changes
          uses: stefanzweifel/git-auto-commit-action@v4
          with:
            commit_message: "fix linting warning"
            commit_user_name: "linter-bot"
            commit_user_email: "linter-bot@users.noreply.github.com"
