name: Request URL and Show Status Code

on:
  push:
    branches:
      - main

jobs:
  request-url:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Request URL
        run: |
          STATUS=$(curl -s -o /dev/null -w "%{http_code}" https://book.icfi.ir/book/39283/%D8%B3%D8%B1%D8%B4%D8%AA-%D9%87%D9%88%D8%B4-%D9%88-%D9%85%D8%B4%DA%A9%D9%84%D8%A7%D8%AA-%D8%B1%D9%81%D8%AA%D8%A7%D8%B1%DB%8C?paginatedParams=page%3D11%26size%3D12%26exhibitorId%3D318)
          echo "Status code: $STATUS"
